export const ONE_SECOND_IN_MS = 1000;

export const ONE_MINUTE_IN_MS = 60 * ONE_SECOND_IN_MS;

export const ONE_HOUR_IN_MS = 60 * ONE_MINUTE_IN_MS;

const ONE_MINUTE_IN_SECONDS = 60;

const ONE_HOUR_IN_SECONDS = 60 * ONE_MINUTE_IN_SECONDS;

export const ONE_DAY_IN_SECONDS = 24 * ONE_HOUR_IN_SECONDS;

export const ONE_YEAR_IN_SECONDS = 365 * ONE_DAY_IN_SECONDS;

export const RETRY_AFTER_SECONDS = 1;
